fix: upgrade apify-client to 1.12.2 to resolve import error
apify-client 1.8.1 has an incompatible dependency on apify-shared
causing ImportError: cannot import name 'ignore_docs' from
'apify_shared.utils' at container startup.